### ISSUE TITLE
BUG: 查询账单下载地址 billDownloadQuery 接口出错

### ISSUE THREAD

**Issue by jerryhu** [Luncher/alipay#34]
查询账单下载地址 billDownloadQuery 接口报错:

```javascript
2018-07-24 11:50:11,094 ERROR 1093 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: Cannot read property 'code' of undefined
    at isSucceed (/.../node_modules/alipay-mobile/lib/index.js:99:43)
    at Alipay.makeResponse (/.../node_modules/alipay-mobile/lib/index.js:107:11)
    at /.../node_modules/alipay-mobile/lib/index.js:132:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
**可能是 config.ALIPAY_API_LIST列表未添加 alipay.data.dataservice.bill.downloadurl.query 的原因**

**Comment by jerryhu** [comment]
#### alipay/src/config/index.js 文件修改如下:

```javascript
ALIPAY_API_LIST: {
    'alipay.trade.query': '订单查询',
    'alipay.trade.refund': '交易退款',
    'alipay.trade.cancel': '取消订单',
    'alipay.trade.precreate': '预创建订单',
    'alipay.trade.close': '关闭交易',
    'alipay.trade.create': '创建交易',
    'alipay.trade.order.settle': '交易结算',
    'alipay.trade.fastpay.refund.query': '交易退款查询',
    'alipay.trade.app.pay': '生成创建订单所需参数',
    'alipay.fund.trans.toaccount.transfer': '单笔转账到支付宝账户接口',
    'alipay.data.dataservice.bill.downloadurl.query': '查询账单下载地址接口', // <-- 需添加的代码
    'async.notify': '异步通知' // 自定义
  }
```

**Comment by Luncher** [comment]
@jerryhu  你提一个PR吧

**Comment by Luncher** [comment]
版本发布了，你试一试：）

**Comment by Luncher** [comment]
发布了，你看一看

**Comment by jerryhu** [comment]
OK, 更新了版本2.2.6, billDownloadQuery 接口调用成功, bug已修复

**Comment by Luncher** [comment]
👌
