### ISSUE TITLE
安装后报错 Error: Cannot find module 'src/config'

### ISSUE THREAD

**Issue by litufu** [Luncher/alipay#41]
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'src/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by litufu** [comment]
错误出现在alipay-mobile\src\validator\schema\create_app_order.ts
import { GoodsType } from 'src/config'

**Comment by Luncher** [comment]
@litufu 修复了，谢谢反馈

**Comment by MeloDai** [comment]
这个错误还在的

**Comment by MeloDai** [comment]
感觉上应该是修复了，但是现在npm只能安装3.0.3版本。3.0.4装不了
