### ISSUE TITLE
TypeError: Cannot read property 'app_id' of null

### ISSUE THREAD

**Issue by niannings** [Luncher/alipay#48]
`const options = {
  app_id: '2016080100137766',
  appPrivKeyFile: read('./keys/app_priv_key.pem'),
  alipayPubKeyFile: read('./keys/alipay_public_key.pem')
}

const service = new Alipay(options)
const data = {
  subject: '辣条',
  out_trade_no: '1232423',
  total_amount: '100'
}
const result = service.createOrder(data)`

**Comment by Luncher** [comment]
错误日志有木有

**Comment by xinlingqudongX** [comment]
改下/dist/validator/index.js下面的参数初始化，我根据soucemap在源代码还没找到这个初始化的地方，可能是我没看仔细吧

**Comment by klren0312** [comment]
我也遇到相同问题
```
TypeError: Cannot read property 'app_id' of null
    at Validator.validate (D:\1file\alipayTest\node_modules\alipay-mobile\dist\validator\index.js:71:31)
    at D:\1file\alipayTest\node_modules\alipay-mobile\dist\validator\index.js:99:27
    at new Promise (<anonymous>)
    at Validator.run (D:\1file\alipayTest\node_modules\alipay-mobile\dist\validator\index.js:96:16)
    at Object.validateBasicParams (D:\1file\alipayTest\node_modules\alipay-mobile\dist\validator\index.js:111:21)
    at Alipay.validateBasicParams (D:\1file\alipayTest\node_modules\alipay-mobile\dist\index.js:58:36)
    at Alipay.validateParams (D:\1file\alipayTest\node_modules\alipay-mobile\dist\index.js:66:18)
    at Alipay.createAppOrder (D:\1file\alipayTest\node_modules\alipay-mobile\dist\index.js:173:21)
    at Alipay.createOrder (D:\1file\alipayTest\node_modules\alipay-mobile\dist\index.js:169:21)
    at Object.<anonymous> (D:\1file\alipayTest\test.js:23:9)
```

**Comment by klren0312** [comment]
我也遇到相同问题
```
TypeError: Cannot read property 'app_id' of null
    at Validator.validate (D:\1file\alipayTest\node_modules\alipay-mobile\dist\validator\index.js:71:31)
    at D:\1file\alipayTest\node_modules\alipay-mobile\dist\validator\index.js:99:27
    at new Promise (<anonymous>)
    at Validator.run (D:\1file\alipayTest\node_modules\alipay-mobile\dist\validator\index.js:96:16)
    at Object.validateBasicParams (D:\1file\alipayTest\node_modules\alipay-mobile\dist\validator\index.js:111:21)
    at Alipay.validateBasicParams (D:\1file\alipayTest\node_modules\alipay-mobile\dist\index.js:58:36)
    at Alipay.validateParams (D:\1file\alipayTest\node_modules\alipay-mobile\dist\index.js:66:18)
    at Alipay.createAppOrder (D:\1file\alipayTest\node_modules\alipay-mobile\dist\index.js:173:21)
    at Alipay.createOrder (D:\1file\alipayTest\node_modules\alipay-mobile\dist\index.js:169:21)
    at Object.<anonymous> (D:\1file\alipayTest\test.js:23:9)
```

**Comment by wisdomzj** [comment]
你们怎么解决的，也是遇到类似问题

**Comment by klren0312** [comment]
> 你们怎么解决的，也是遇到类似问题

我放弃了 发现直接用官方的库好用的很... 当初想多了
